# Generated by Django 4.2.13 on 2024-07-03 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_item_about_item_big_cat_item_date_item_off_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='date',
        ),
    ]
