# Generated by Django 4.2.13 on 2024-07-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_item_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, default='def.jpg', upload_to=''),
        ),
    ]
