# Generated by Django 4.2.13 on 2024-07-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='about',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='item',
            name='big_cat',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='item',
            name='off',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='item',
            name='properties',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default=None),
        ),
        migrations.AddField(
            model_name='item',
            name='sml_cat',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
